[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_program = "9WRa3Dpz2Di4awYBmdvUwh9gawrQLi29exR8RctkEMhj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/marcho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
