[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_program = "2Qo3f8jvQZ8mJqLdm95DPBsC19EKKwCi3ohjGZkBrTC1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/marcho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
